include:
  - board: nice_nano_v2
    shield: corne_left
    snippet: studio-rpc-usb-uart
    kconfig: CONFIG_ZMK_STUDIO=y
  - board: nice_nano_v2
    shield: corne_right
    snippet: studio-rpc-usb-uart
    kconfig: CONFIG_ZMK_STUDIO=y

alphas: qwerty
